### ISSUE TITLE
Is it possible to use external function in select query and used returned result as columns

### ISSUE THREAD

**Issue by itsursujit** [noborus/trdsql#129]
Is it possible to map a field to a function and use the returned results as columns?

For e.g.
```

func A(phone string) []string {

}

func B(ip string) string {

}

```
So it would be like

`trd.Exec("SELECT phone, A(phone) as field1,field2,field3, ip, B(ip) as location FROM test.csv"`

**Comment by noborus** [comment]
SQL is processed on the database side (SQLite3 etc.), so it's difficult to write as you wrote it.

You can pass the result received from the database to the function.
To do this, you need to replace the writer or exporter of the function that processes the result.
