### ISSUE TITLE
Standard Deviation

### ISSUE THREAD

**Issue by pannalal** [noborus/trdsql#140]
While putting SQL, I need to compute standard deviation of some columns like: "select stddev(c1), stddev(c2) from test.csv"

It displays: ERROR(EXPORT):SQL:no such function: stddev

**Comment by noborus** [comment]
Sorry, stddev is not available because it is not included in SQLite3.
Recommend using PostgreSQL driver or MySQL driver.

**Comment by pannalal** [comment]
Thanks

**Comment by pannalal** [comment]
Please guide how can we use "https://github.com/dinedal/go-sqlite3-extension-functions" with trdsql. Thanks
