### ISSUE TITLE
Want to get Integer values from JSON data instead of exponential notation

### ISSUE THREAD

**Issue by suzuki** [noborus/trdsql#151]
## About

- I want to get Integer values from JSON data like CSV parser

## Version

```
% trdsql --version
trdsql version v0.8.0
```

### data.csv

```
id,name
1000000,"foo"
1000001,"bar"
```

### Result

- The results are integer values

```
% trdsql -icsv -ih "SELECT * FROM data.csv"
1000000,foo
1000001,bar
```

### data.json

```
[
  {
    "id": 1000000,
    "name": "foo"
  },
  {
    "id": 1000001,
    "name": "bar"
  }
]
```

### Result

- The results are exponential notation
    - `1e+06`
    - `1.000001e+06`
- I want to get these values as integer

```
 % trdsql -ijson "SELECT * FROM data.json"
1e+06,foo
1.000001e+06,bar
```

**Comment by noborus** [comment]
Thank you very much.
This was wrong because trdsql has a policy of not doing extra conversions as much as possible.
