### ISSUE TITLE
Question. Can trdsql query by a column has no value(null or empty)

### ISSUE THREAD

**Issue by mailsanchu** [noborus/trdsql#175]

**Comment by noborus** [comment]
trdsql considers an empty string ('') if it has no value.

```test.csv
a,b,c
,,2
1,2,3
```
```console
trdsql -ih -omd "SELECT * FROM test.csv WHERE a=''"
```

| a | b | c |
|---|---|---|
|   |   | 2 |

The number of columns counts the first row by default.
You can change the number of rows that determine the number of columns with `-ir num`.

**Comment by mailsanchu** [comment]
Happy to close this question

**Comment by mailsanchu** [comment]
![image](https://user-images.githubusercontent.com/32928538/148274416-e9af94a5-32de-41cb-880d-3f4f44f278d7.png)
Any option to use the full terminal width?

**Comment by noborus** [comment]
There is no such option.
You can create another issue as a request.
However, depending on the terminal width presents many problems.

**Comment by mailsanchu** [comment]
No bother. I am just checking for any hidden feature :)
