### ISSUE TITLE
Multiple queries

### ISSUE THREAD

**Issue by agguser** [noborus/trdsql#184]
Please support multiple queries. Currently, it seems that only last query is output, e.g.
```
$ trdsql 'select 1; select 2,3'
2,3
```
Note: `union` is not used here because of different number of columns.

A workaround is to run multiple commands (e.g. `trdsql 'select 1'; trdsql 'select 2,3'`), but database will be created multiple times. And if input is from stdin, you have to save it first to share same input for each command.

**Comment by noborus** [comment]
Thank you for the issue.
I hope this can be done, but I don't think it will be used much in practice, and simplicity may be sacrificed.

**Comment by noborus** [comment]
Implemented in v0.20.0. thank you.
