### ISSUE TITLE
`-ijq` does not work correctly from stdin

### ISSUE THREAD

**Issue by ChristianCiach** [noborus/trdsql#186]
Hi! Thanks for creating trdsql - it's awesome!

I just discovered this tool and I think it will on many occasions replace `jq` for me. But I think I've found a minor bug in the current version 0.9.1.

It's best shown using an example. 

This works:
```sh
$ cat customer_basedata.json | trdsql -ijson 'SELECT id, name FROM -::.entities'
```

Also works:
```sh
$ trdsql -ijq '.entities' 'SELECT id, name FROM customer_basedata.json'
```

This doesn't work:
```sh
$ cat customer_basedata.json | trdsql -ijq '.entities' 'SELECT id, name FROM -'
```

Error message:
```
2022/04/22 14:17:01 import: too many columns on -::jq1
```

By the way, version 0.9.1 is missing on docker hub :)

**Comment by noborus** [comment]
The current version first requires the `-ijson` option.

```
cat customer_basedata.json | trdsql -ijson -ijq '.entities' 'SELECT id, name FROM -'
```

I can assume json when using the -ijq option, so I'll consider fixing it.
Thank you very much.
