### ISSUE TITLE
Segmentation fault running the release binary on Mac OS X 10.7.5 (Lion)

### ISSUE THREAD

**Issue by taa1** [noborus/trdsql#19]
I'm trying [trdsql_darwin_amd64.zip](https://github.com/noborus/trdsql/releases/download/v0.4.1/trdsql_darwin_amd64.zip) but I get a segfault immediately when running the program, even with no command line arguments specified:

`$ ./trdsql 
Segmentation fault: 11

./trdsql -help
Segmentation fault: 11
$ `

Is there somewhere that I can find a list of the system requirements for trdsql?

**Comment by noborus** [comment]
I'm sorry. I do not know the requirement of macOS.
I build binaries for macOS with Travis CI.
Reference: https://docs.travis-ci.com/user/reference/osx/#OS-X-Version

You might as well build it yourself.
https://github.com/noborus/trdsql#install

**Comment by taa1** [comment]
Thanks for the reply. Unfortunately the build-it-yourself instructions assume that Go is already installed. Apparently Go is not supported on Mac OS X earlier than 10.8 so I'm out of luck. Oh well.
