### ISSUE TITLE
Error: Cannot tap noborus/tap: invalid syntax in tap!

### ISSUE THREAD

**Issue by greenwar** [noborus/trdsql#190]
==> Tapping noborus/tap
Cloning into '/usr/local/Homebrew/Library/Taps/noborus/homebrew-tap'...
remote: Enumerating objects: 181, done.
remote: Counting objects: 100% (75/75), done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 181 (delta 42), reused 24 (delta 10), pack-reused 106
Receiving objects: 100% (181/181), 27.49 KiB | 5.50 MiB/s, done.
Resolving deltas: 100% (98/98), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/noborus/homebrew-tap/pgsp.rb
pgsp: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the noborus/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/noborus/homebrew-tap/pgsp.rb:9

Error: Cannot tap noborus/tap: invalid syntax in tap!

**Comment by noborus** [comment]
Thank you very much.
Since it is an issue in the repository of https://github.com/noborus/homebrew-tap, move the issue.
