### ISSUE TITLE
feature request: support input format yaml file

### ISSUE THREAD

**Issue by someblue** [noborus/trdsql#217]
trdsql is awesome tools!!!

Can you add support for yaml files? Sometimes I need to deal with yaml file, and I need other tool to transfer yaml to json file. It would be better if yaml is supported by trdsql directly.

**Comment by noborus** [comment]
Thank you for your issue. 
I will think about it.

**Comment by noborus** [comment]
Released v0.12.0 with YAML support.
thank you.
