### ISSUE TITLE
Ignores nullable columns

### ISSUE THREAD

**Issue by avoidik** [noborus/trdsql#269]
Hello,

Great tool, I was exploring some data, and stumbled upon an issue, when optional columns have been dropped, here is a basic repro case:

```terminal
$ echo -e '{"method": "GET"}\n{"method": "POST", "meta.user": "with.dot"}' | trdsql "SELECT * FROM -"
"{""method"": ""GET""}"
"{""method"": ""POST"""
```

is this something expected?

**Comment by noborus** [comment]
yes.
If the number of columns is not constant, you need to specify the number of rows to pre-read.
It is recommended to specify it as follows.

```console
echo -e '{"method": "GET"}\n{"method": "POST", "meta.user": "with.dot"}' |trdsql -ir 2 "SELECT * FROM -"
"{""method"": ""GET""}",
"{""method"": ""POST"""," ""meta.user"": ""with.dot""}"
```

**Comment by avoidik** [comment]
Thanks, that's it!
