### ISSUE TITLE
We add trdsql in the x-cmd pkg

### ISSUE THREAD

**Issue by edwinjhlee** [noborus/trdsql#270]
Hello, frineds in trdql. 

I don's know whether it is appropriate, but we create this issue just to tell you we like trdsql, we just add trdsql in x-cmd pkg and record serveral scriptplay demos.

https://x-cmd.com/pkg/trdsql#trdsql
https://x-cmd.com/1min/trdsql#trdsql

**Comment by noborus** [comment]
Thank you for the issue.
I'll consider adding a link.
