### ISSUE TITLE
Make this project dependency ready

### ISSUE THREAD

**Issue by stipo42** [noborus/trdsql#41]
I would like to use this as a dependency of my own application, however I cannot use it as such because all the code is in the `main` package.

Please move supporting code to it's own package and reference from your main.go so this can be used from other go programs.

Moreover, structs appear to use all private fields, so those would need to be updated as well. 

Please also provide an option to supply an input stream to the TRDSQL struct, instead of assuming a file.

**Comment by noborus** [comment]
Thank you for the great suggestions!

I will do according to your suggestion.

**Comment by noborus** [comment]
I committed to the master branch.
```
go get github.com/noborus/trdsql@master
```
try it.

**Comment by noborus** [comment]
I just released v0.6.1.
I hope you find it useful.

**Comment by noborus** [comment]
Close, because the package separation is complete.
If there is a problem, please reopen or create another issue.
