### ISSUE TITLE
multiple files syntax error

### ISSUE THREAD

**Issue by Spacewalker2** [noborus/trdsql#62]
Hello, first of all great tool! I use it a lot. If try to work with multiple files I get an error.

```
$ trdsql -ih -id ";" "SELECT * FROM *csv"
2019/07/31 16:41:55 ERROR: SQL:near "*": syntax error
[SELECT * FROM *csv]
```

This works fine.
```
$ trdsql -ih -id ";" "SELECT * FROM file.csv"
```
Did I something wrong?

**Comment by noborus** [comment]
Thank you for using trdsql.

> trdsql -ih -id ";" "SELECT * FROM *csv"
> 2019/07/31 16:41:55 ERROR: SQL:near "*": syntax error
> [SELECT * FROM *csv]

First check the version of trdsql.

```
$ trdsql -version
```

Wildcards can be used from 0.5.0.
If it is old, please try a new version.

If you still have problems, please send the output with the -debug option.

```
$ trdsql -debug -ih -id ";" "SELECT * FROM *csv"
```

**Comment by Spacewalker2** [comment]
> First check the version of trdsql.

Sorry I should have do this in the first plane. The version is 0.4.1 so I think this will solve my problem. I thought the distro version was the current version.
